# src/main/resources/application.properties
server.port=8081
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.main.banner-mode=off

#logging.level.org.springframework=DEBUG

upload.dir=uploads
thumbnail.dir=thumbnails
thumbnail.maxwidth=280
thumbnail.maxheight=280