# src/main/resources/application.properties
server.port=8081
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.main.banner-mode=off

#logging.level.org.springframework.boot.autoconfigure=DEBUG
#logging.level.org.springframework=DEBUG

upload.dir=uploads
thumbnail.dir=thumbnails
thumbnail.maxwidth=280
thumbnail.maxheight=280

spring.datasource.url=jdbc:h2:file:./data/photo_gallery;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.url=jdbc:h2:mem:photodb
#spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
#spring.h2.console.settings.web-allow-others=true

#spring.devtools.add-properties=true

logging.file.path=logs