# src/main/resources/application.properties
server.port=8081
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.main.banner-mode=off

#logging.level.org.springframework.boot.autoconfigure=DEBUG
#logging.level.org.springframework=DEBUG

upload.dir=uploads
thumbnail.dir=thumbnails
thumbnail.maxwidth=280
thumbnail.maxheight=280

spring.datasource.url=jdbc:h2:file:./data/photo_gallery;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.file.path=logs

#llm.tagging.prompt=tag this image, return as comma-separated list
llm.tagging.prompt=Describe the image using ONLY a comma-separated list of keywords. Rules: NO sentences, NO extra text before or after, NO numbering, NO bullet points, NO Notes, NO explanations, NO summary, NO OCR
llm.python.vision.script=python/smolvlm_vision_cli.py
llm.python.text.script=python/smolvlm_text_cli.py
llm.python.executable=python
llm.ollama.url=http://localhost:11434